name: Update Petshop
on:
  push:
    branches:
    - main
jobs:
  refresh:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          path: local
      - name: run generator
        run: docker run openapitools/openapi-generator-cli generate -i ${GITHUB_WORKSPACE}/local/petstore.yaml -g aspnetcore -o ${GITHUB_WORKSPACE}/out/aspnetcore --additional-properties=aspnetCoreVersion=6.0
