name: Update Petshop
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/main.yml
jobs:
  refresh:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
        with:
          path: local
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: local
      - name: install generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: run generator
        run: |
          cd local
          openapi-generator-cli generate -g aspnetcore -i petstore.yaml -c config.yaml -o out/aspnetcore --additional-properties=aspnetCoreVersion=6.0
      - name: commit and push output
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'githubactions@example.com'
          git add ./out
          git commit -m "Updated Petstore output"
          git push 
