name: Update Petshop
on:
  push:
    branches:
    - main
jobs:
  refresh:
    runs-on: ubuntu-latest    
    steps:
      - name: run generator
        run: docker run openapitools/openapi-generator-cli generate -i ${GITHUB_WORKSPACE}/petstore.yaml -g aspnetcore -o ${GITHUB_WORKSPACE}/out/aspnetcore --additional-properties=aspnetCoreVersion=6.0
