name: Update Petshop
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/main.yml
jobs:
  refresh:
    runs-on: ubuntu-latest  
    container: 
      image: openapitools/openapi-generator-cli
      volumes:
        - mnt:/local      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          path: local
      - name: run generator
        run: ls
      #  run: docker run openapitools/openapi-generator-cli generate -i local/petstore.yaml -g aspnetcore -o local/out/aspnetcore --additional-properties=aspnetCoreVersion=6.0
