name: Update Petshop
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/main.yml
jobs:
  refresh:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
        with:
          path: local
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: run generator
        run: |
          cd local
          openapi-generator-cli generate -g aspnetcore -i petstore.yaml -c config.yaml -o out/aspnetcore --additional-properties=aspnetCoreVersion=6.0
          ls -R
